config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"

  # Authentication routes
  scope controller: :sessions do
    get :login, action: :new
    post :login, action: :create
    delete :logout, action: :destroy
  end

  resources :passwords, param: :token

  resources :users, except: [ :index, :show ]
  resources :user_invitations, except: [ :show, :edit ]

  resources :workspaces, except: :index do
    resources :projects, except: :index do
      resources :tasks, except: :index
    end
  end
end

app/views/layouts/shared/_head.html.erb
<title><%= t("app.title") %></title>

<meta name="description" content="Projects 는 개인 사이드 프로젝트를 쉽고 효율적으로 관리하고, 신뢰할 수 있는 동료 개발자와 협업할 수 있는 프라이빗 작업 관리 서비스입니다.">
<meta name="keywords" content="개인 프로젝트 관리, 사이드 프로젝트 관리, 태스크 관리, 작업 관리, 개발자 협업, 개인 협업툴">
<meta name="author" content="Joungsik">

<meta property="og:title" content="<%= t("app.title") %>">
<meta property="og:description" content="Projects로 개인 프로젝트를 효율적으로 관리하고 신뢰하는 개발자들과 협업하세요.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://projects.joungsik.com">
<meta property="og:site_name" content="Projects">
<meta property="og:image" content="/image.png">

<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
<%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

<link rel="icon" href="/icon.png" type="image/png">
<link rel="apple-touch-icon" href="/icon.png">

<%# Includes all stylesheet files in app/assets/stylesheets %>
<%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-C5FQCB9D6C"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }

  gtag('js', new Date());

  gtag('config', 'G-C5FQCB9D6C');
</script>

app/views/layouts/shared/_htmldoc.html.erb
<!DOCTYPE html>
<html lang="ko">
  <head>
    <%= render "layouts/shared/head" %>
    <%= yield :head %>
  </head>

  <body class="min-h-screen bg-gray-100" data-controller="sidebar">
    <%= render "shared/notice" %>

    <%= yield %>

    <%= turbo_frame_tag "modal" %>
  </body>
</html>